version: "3.8"

services:
  wayofsecurity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wayofsecurity-dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
